version: "3.7"
services:
  db:
    image: mysql
    container_name: db
    command:
      - --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Impacta
      - MYSQL_DATABASE=cars-for-sale
    ports:
      - "3306:3306"
  back:
    container_name: back
    build: ./CarsForSaleBack
    ports:
      - "8080:8080"
    depends_on: [db]
    environment:
      - DB_URL=jdbc:mysql://localhost:3306/cars-for-sale
      - DB_USERNAME=root
      - DB_PASSWORD=Impacta
  front:
    container_name: front
    build: ./CarsForSaleFront
    ports:
      - "4200:4200"
    depends_on: [back]
    environment:
      - BACKEND_URL=back